[package]
name = "system-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
winreg = "0.50"
ureq = "2"
rquickjs = "0.9.0"
dns-lookup = "1"
url = "2"
regex = "1"
chrono = { version = "0.4", features = ["clock"] }
